#!/bin/bash

# Instruções para Configurar OAuth com kzstore.ao
# Data: 9 Dezembro 2025

echo "🔐 Configuração OAuth - Google & Facebook"
echo "=========================================="
echo ""

# Cores
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}📋 URLs de Callback Atualizadas:${NC}"
echo ""
echo "Domínio: https://kzstore.ao"
echo "Backend: https://kzstore-backend.fly.dev"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}1️⃣ GOOGLE OAUTH CONFIGURATION${NC}"
echo -e "${BLUE}═══════════════════════════════════════════${NC}"
echo ""
echo "Acesse: https://console.cloud.google.com/apis/credentials"
echo ""
echo "✅ Authorized JavaScript origins:"
echo "   • https://kzstore.ao"
echo "   • https://kzstore-backend.fly.dev"
echo ""
echo "✅ Authorized redirect URIs:"
echo "   • https://kzstore-backend.fly.dev/api/auth/google/callback"
echo "   • https://kzstore.ao/api/auth/google/callback"
echo ""
echo -e "${YELLOW}Passo a passo:${NC}"
echo "1. Selecione seu projeto Google Cloud"
echo "2. Vá em: APIs & Services → Credentials"
echo "3. Clique no OAuth 2.0 Client ID criado"
echo "4. Em 'Authorized JavaScript origins', adicione:"
echo "   - https://kzstore.ao"
echo "   - https://kzstore-backend.fly.dev"
echo "5. Em 'Authorized redirect URIs', adicione:"
echo "   - https://kzstore-backend.fly.dev/api/auth/google/callback"
echo "6. Clique em 'Save'"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}2️⃣ FACEBOOK OAUTH CONFIGURATION${NC}"
echo -e "${BLUE}═══════════════════════════════════════════${NC}"
echo ""
echo "Acesse: https://developers.facebook.com/apps"
echo ""
echo "✅ Valid OAuth Redirect URIs:"
echo "   • https://kzstore-backend.fly.dev/api/auth/facebook/callback"
echo "   • https://kzstore.ao/api/auth/facebook/callback"
echo ""
echo "✅ App Domains:"
echo "   • kzstore.ao"
echo "   • kzstore-backend.fly.dev"
echo ""
echo -e "${YELLOW}Passo a passo:${NC}"
echo "1. Selecione seu app Facebook"
echo "2. Vá em: Settings → Basic"
echo "3. Em 'App Domains', adicione:"
echo "   - kzstore.ao"
echo "   - kzstore-backend.fly.dev"
echo "4. Vá em: Products → Facebook Login → Settings"
echo "5. Em 'Valid OAuth Redirect URIs', adicione:"
echo "   - https://kzstore-backend.fly.dev/api/auth/facebook/callback"
echo "6. Clique em 'Save Changes'"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}3️⃣ VERIFICAR CONFIGURAÇÕES ATUAIS${NC}"
echo -e "${BLUE}═══════════════════════════════════════════${NC}"
echo ""
echo "Variáveis de ambiente configuradas no Fly.io:"
echo ""

fly secrets list -a kzstore-backend 2>&1 | grep -E "NAME|VITE_APP_URL|GOOGLE|FACEBOOK"

echo ""
echo -e "${BLUE}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}4️⃣ TESTAR OAUTH${NC}"
echo -e "${BLUE}═══════════════════════════════════════════${NC}"
echo ""
echo "🧪 Teste de Login:"
echo ""
echo "1. Acesse: https://kzstore.ao"
echo "2. Clique em 'Entrar' ou 'Cadastrar'"
echo "3. Escolha 'Continuar com Google' ou 'Continuar com Facebook'"
echo "4. Você deve ser redirecionado para:"
echo "   - Página de autorização Google/Facebook"
echo "   - Após aprovar, volta para: https://kzstore.ao"
echo "   - Mensagem: 'Login realizado com sucesso! Bem-vindo(a)!'"
echo ""
echo -e "${YELLOW}Se der erro:${NC}"
echo "• Verifique o console do navegador (F12)"
echo "• Veja se a URL de callback está correta"
echo "• Confirme que adicionou as URLs no Google/Facebook"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}5️⃣ LOGS DE DEBUG${NC}"
echo -e "${BLUE}═══════════════════════════════════════════${NC}"
echo ""
echo "Ver logs do backend em tempo real:"
echo ""
echo -e "${YELLOW}fly logs -a kzstore-backend${NC}"
echo ""
echo "Procure por:"
echo "• 🔵 [OAuth Google] ..."
echo "• 🔵 [OAuth Facebook] ..."
echo "• ✅ [OAuth] Token recebido..."
echo "• ❌ [OAuth] Erro..."
echo ""

echo -e "${GREEN}✨ Configuração completa!${NC}"
echo ""
echo "Próximos passos:"
echo "1. Configure URLs no Google Cloud Console"
echo "2. Configure URLs no Facebook Developers"
echo "3. Teste o login em https://kzstore.ao"
echo "4. Verifique logs com: fly logs -a kzstore-backend"
